name: Preprocessing Pipeline

on:
  push:
    paths:
      - 'Preprocessing/automate_Ginanti_Riski.py'
      - 'dataset_raw/**'
      - '.github/workflows/main.yml'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: |
        mkdir -p Preprocessing/car_preprocessing
        python Preprocessing/automate_Ginanti_Riski.py

    - name: Commit and push processed files
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}  # Mengambil token dari GitHub Secrets
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add Preprocessing/car_preprocessing/*.csv
        git add Preprocessing/car_preprocessing/*.pkl
        git commit -m "Add processed dataset from preprocessing pipeline"
        git push https://x-access-token:${GH_TOKEN}@github.com/GinantiRiski1/Eksperimen_SML_GinantiRiski.git HEAD:Main
